server:
  port: 80
  
spring:
  application:
    name: cloud-consumer-order-feign80
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka